### ISSUE TITLE
style the frontend

### ISSUE THREAD

**Issue by yactouat** [yactouat/SWS_waste-sorter#2]

**Comment by ritik2358** [comment]
Hey @yactouat, I want to work on this issue.
So, could you please assign me the same.

**Comment by yactouat** [comment]
hey @ritik2358 , thank you for participating ! the only requirements here are that it should not be as ugly as it is now; I'm working on the AI model right now => https://github.com/yactouat/learning_AI/tree/master/notebooks/waste-sorter and I'm gonna export a new model soon

**Comment by ritik2358** [comment]
Thank you @yactouat for assigning me this issue. I'll do the necessary changes and then raise a PR.

**Comment by yactouat** [comment]
hey @ritik2358 , how it going with the issue ?

**Comment by ritik2358** [comment]
I started modifying the frontend but I want to talk to you over few things regarding the website 
So, Can we connect and discuss the required thing ?

**Comment by yactouat** [comment]
https://github.com/yactouat/waste_sorter_demo/issues/4#issuecomment-1597709156

**Comment by yactouat** [comment]
re opening the issue as we need now to add in the CI building the app' and deploying it

also we need to wire the actual API call to the backend in the UI
