### ISSUE TITLE
show projects contributors in the app'

### ISSUE THREAD

**Issue by yactouat** [yactouat/SWS_waste-sorter#33]

**Comment by aharonYK** [comment]
hello can i fix this issue for you?

**Comment by yactouat** [comment]
hey @aharonYK, thanks for contributing ! yea that would be great, just for the repo and make a PR (and of course put yourself in the contributors list ;))

**Comment by yactouat** [comment]
closed with https://github.com/yactouat/SWS_waste-sorter/pull/41
