### ISSUE TITLE
internationalize the frontend

### ISSUE THREAD

**Issue by yactouat** [yactouat/SWS_waste-sorter#34]
- [ ] flag selector in navbar
- [x] English is the default language
- [x] French is a supported language

**Comment by etnms** [comment]
Hey, I can work on the French translation. Is it translation of the frontend? The documentation? Or both?

**Comment by yactouat** [comment]
hey @etnms , thanks a lot ! actually that would be just the front, renaming the ticket to `internationalize the frontend`; it could be great if we had a flag selector in the navbar that would allow the user to select a language

**Comment by etnms** [comment]
Alright great, quick follow up questions: - do you plan on having more than English and French? - did you think of incorporating i18n for translations or a custom way to display languages?

**Comment by yactouat** [comment]
the ultimate endgame of the app' would be to support several cities and color codes/trash bins systems, so eventually multiple languages would need to supported; we could be based on this example => https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple with a dynamic [config](https://github.com/i18next/react-i18next/blob/master/example/react-typescript/simple/src/i18n/config.ts) that would change with the selected flag from the UI

tell me what you think !

**Comment by etnms** [comment]
Yeah, if you want more than two languages i18n is a good and practical solution I believe.
Thanks for the info, I'll work on that then.

**Comment by yactouat** [comment]
Thank you !
